print("==================================================")
print("Area de Teste")
print("==================================================")
print("\n")
print("Ola, Mundo")
print("\n")
print("Ola")
